name: wolkezoo_module
description: wolkezoo 通用组件
version: 0.0.2
homepage: https://gitee.com/ee_lrg

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.0.0
  flutter_screenutil: ^5.9.0
  dio: ^5.4.1
  flustars: ^2.0.1
  nanoid: ^1.0.0
  uuid: ^4.3.3
  ellipsized_text: ^1.2.0
  path: ^1.9.0

  # 日志包
  loggy: ^2.0.3
  pretty_dio_logger: ^1.3.1

  # 加密包
  encrypt: ^5.0.3
  crypto: ^3.0.3
  basic_utils: ^5.7.0
  cryptography: ^2.7.0

  # 检查越狱
  flutter_jailbreak_detection: ^1.10.0
  # 网络检查
  connectivity_plus: ^5.0.2
  flutter_network_connectivity: ^0.0.6
  # 吐司弹框
  fluttertoast: ^8.2.4
  # 精准网络时间
  ntp: ^2.0.0
  intl: ^0.19.0
  get_time_ago: ^1.3.1

  # 权限获取
  permission_handler: ^11.3.0

  # 动画选择
  msh_checkbox: ^2.0.1

  # 计时器
  timer_count_down: ^2.2.2

  # 动画底部导航栏
  animated_bottom_navigation_bar: ^1.3.3

  # 文件选择
  file_picker: ^6.2.0

  # 动画加载
  loading_animation_widget: ^1.2.0+4

  # 视频包
  video_thumbnail: ^0.5.3

  #  图片缓存库
  extended_image: ^8.2.0

  xxh3: ^1.0.1
  animate_do: ^3.3.4
  easy_debounce: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
